### ISSUE TITLE
dx version

### ISSUE THREAD

**Issue by bmp** [ublue-os/framework#13]
Hello, Is there a developer version? I looked at https://github.com/orgs/ublue-os/packages?repo_name=framework and was unable to see any of the usual `dx` version.

**Comment by bobslept** [comment]
The search didn't fool you. At this moment there is no dx version. That is a variant of `bluefin`.

**Comment by bobslept** [comment]
I will close this one because the looked for variant of dx is now under this repo. That is the `bluefin-dx-framework` variant. Feel free to re-open when needed.
