### ISSUE TITLE
Justfile needs a shortcut for 12th gen Framework 13

### ISSUE THREAD

**Issue by castrojo** [ublue-os/framework#44]
We should find a smart way of adding multigenerations to the just shortcuts. The 12th gen needs this done: https://github.com/FrameworkComputer/linux-docs/blob/main/Fedora38-12thGen.md

The kargs from the existing `just framework-13` probably work fine, but we should mirror the official docs when we can. 

File is here: 

https://github.com/ublue-os/framework/blob/main/system_files/just/custom.just

**Comment by bobslept** [comment]
Maybe we could use `just framework-13` for last gen, and use `just framework-13-gen12` for the 12th gen, and so on? When new a gen comes out, the current move to `just framework-13-gen13` or something?

Or maybe read gen information from `/proc/cpuinfo` and act on that?

If we can a few `grep -m 1 "model name" /proc/cpuinfo` from framework users that would be awesome. On the framework forums I found a 12th gen one.

```
model name      : 12th Gen Intel(R) Core(TM) i5-1240P
model name	: 12th Gen Intel(R) Core(TM) i7-1260P
```

Seems doable by the looks of those two!
