### ISSUE TITLE
Requesting Solaar

### ISSUE THREAD

**Issue by bmp** [ublue-os/framework#59]
I had previously [requested](https://github.com/ublue-os/bluefin/issues/453#issue-1877001953) Solaar on Bluefin and it was incorporated fairly quickly.

Can this just be added to packages.json? Should I do a PR?

**Comment by EyeCantCU** [comment]
Hi! Solaar is something that would fall outside of scope for these images unfortunately. Please look at my response here:

https://github.com/ublue-os/framework/issues/60#issuecomment-1850066021

Thank you!

**Comment by bmp** [comment]
Sure, I'll look at spinning up my own version with customization.

**Comment by EyeCantCU** [comment]
Sweet. Highly recommend it. It's a great learning process
