### ISSUE TITLE
Possibility of a dx version?

### ISSUE THREAD

**Issue by bmp** [ublue-os/framework#60]
As I continue to daily drive the `kinoite-framework` image, I'd like to request a kinoite-dx-framework image too, please let me know if I can help with it and point me to the correct files to modify and would be happy to contribute.

**Comment by EyeCantCU** [comment]
Hello, there. Kinoite Framework images are meant to align with the goals of main images while providing hardware compat and tweaks for Framework devices. Unfortunately, a Kinoite Framework DX image falls out of scope (at least in relation to the images hosted here)

However, feel free to create your own image that adds tooling that you need. You can read up on that here:

https://universal-blue.org/tinker/make-your-own/

**Comment by bmp** [comment]
@EyeCantCU Thank you for the response!

**Comment by EyeCantCU** [comment]
No problem. Happy to help :)
